-- Inserting the first row
INSERT INTO sunbird.user (
    id,
    rootorgid,
    status,
    roles,
    username
) VALUES (
    '19d81ef7-36ce-41fe-ae2d-c8365d977be4',
    '0123221617357783046602',
    2,
    ['teacher'],
    'te**************@yopmail.com'
);

-- Inserting the second row
INSERT INTO sunbird.user (
    id,
    rootorgid,
    status,
    roles,
    username
) VALUES (
    '96d92794-ce98-449d-a11e-494701f21f2d',
    '0137038836873134080',
    1,
    ['teacher'],
    'te**************@yopmail.com'
);

-- Inserting the third row
INSERT INTO sunbird.user (
    id,
    rootorgid,
    status,
    roles,
    username
) VALUES (
    '14c26d33-2006-4204-8f42-87823ca93612',
    '0137038836873134080',
    2,
    ['teacher'],
    'te**************@yopmail.com'
);

-- Inserting the fourth row
INSERT INTO sunbird.user (
    id,
    rootorgid,
    status,
    roles,
    username
) VALUES (
    'ae25447d-ec99-4d77-a733-fe2bfe623a96',
    '0137038836873134080',
    2,
    ['teacher'],
    'te**************@yopmail.com'
);

-- Inserting the fifth row
INSERT INTO sunbird.user (
    id,
    rootorgid,
    status,
    roles,
    username
) VALUES (
    'fca2925f-1eee-4654-9177-fece3fd6afc9',
    '0137038836873134080',
    2,
    ['student'],
    '42*@yopmail.com'
);
