---
- name: delete files and folders - deleting {{ oss_bucket_name  }}/{{ object_prefix }}
  shell: oci os object bulk-delete -bn {{oss_bucket_name}} --prefix {{object_prefix}} --force
  async: 1800
  poll: 0