blob_container_name: "{{ cloud_storage_artifacts_bucketname }}"
blob_file_name: "{{ artifact }}"
local_file_or_folder_path: "{{ artifact_path }}"
storage_account_name: "{{ cloud_artifact_storage_accountname }}"
storage_account_key: "{{ cloud_artifact_storage_secret }}"