- name: include vars
  include_vars: "{{ cloud_service_provider }}_creds.yml"

- name: upload artifact from azure storage
  include_role:
    name: "{{ cloud_service_provider }}-cloud-storage"
    tasks_from: upload.yml
  tags:
    - upload

- name: download artifact from azure storage
  include_role:
    name: "{{ cloud_service_provider }}-cloud-storage"
    tasks_from: download.yml
  tags:
    - download
