- name: download artifact from azure storage
  include_role:
    name: "{{ cloud_service_provider }}-cloud-storage"
    tasks_from: upload.yml
{{- with azure_creds }}
  vars:
{{ toYaml . | indent 4 }}
{{- end }}
  tags:
    - upload

- name: download artifact from azure storage
  include_role:
    name: "{{ cloud_service_provider }}-cloud-storage"
    tasks_from: download.yml
  vars: ${${cloud_service_provider}_creds}
  tags:
    - download
