gcp_storage_service_account_name: "{{ cloud_artifact_storage_accountname }}"
gcp_storage_key_file: "{{ cloud_artifact_storage_secret }}"
gcp_bucket_name: "{{ cloud_storage_artifacts_bucketname }}"
gcp_path: "{{ artifact }}"
local_file_or_folder_path: "{{ artifact_path }}"