---
- hosts: localhost
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{sunbird_artifact_storage_account_name}}"
    AZURE_STORAGE_SAS_TOKEN: "{{sunbird_artifact_storage_account_sas}}"
  tasks:
    - name: upload artifact to azure storage
      include_role:
        name: artifacts-upload-azure
      when: cloud_service_provider == "azure"

    - name: upload artifact to oci oss
      include_role:
        name: oci-cloud-storage
        tasks_from: upload.yml
      vars:
        local_file_or_folder_path: "{{ artifact_path }}"
        oss_bucket_name: "{{ oci_artifact_oss_bucket_name }}"
        oss_path: "{{ artifact }}"
      when: cloud_service_provider == "oci"