---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{cloud_private_storage_accountname}}"
    AWS_SECRET_ACCESS_KEY: "{{cloud_private_storage_secret}}"
  roles:
   - lern-data-products-deploy
