---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    AWS_ACCESS_KEY_ID: AKIA57YRBBPVDG6QI52N
    AWS_SECRET_ACCESS_KEY: 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
  roles:
   - lern-data-products-deploy
