---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    sunbird_private_storage_account_name: "{{cloud_private_storage_accountname}}"
    sunbird_private_storage_account_key: "{{cloud_private_storage_secret}}"
  roles:
   - lern-data-products-deploy
