---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    AWS_ACCOUNT_NAME: "{{AKIA57YRBBPVDG6QI52N}}"
    AWS_STORAGE_KEY: "{{djDZqDYWehtx6wm6WqdZeDhUehKyLwrqrPQP3cL7}}"
  roles:
   - lern-data-products-deploy
