---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    account_name: AKIA57YRBBPVDG6QI52N
    storage_key: djDZqDYWehtx6wm6WqdZeDhUehKyLwrqrPQP3cL7
  roles:
   - lern-data-products-deploy
