---
- hosts: "{{remote}}"
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{ analytics_user }}"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{AKIA57YRBBPVDG6QI52N}}"
    AZURE_STORAGE_KEY: "{{djDZqDYWehtx6wm6WqdZeDhUehKyLwrqrPQP3cL7}}"
  roles:
   - lern-data-products-deploy
